<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Rocket</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>17</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>545.3257132619674</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>225.8700941248816</KnownMass>
                    <Density>1780.0</Density>
                    <Material>Carbon fiber</Material>
                    <Name>Nose Cone</Name>
                    <KnownCG>83.78922550072163</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>225.8700941248816</CalcMass>
                    <CalcCG>83.78922550072163</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>135.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>5.0</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts>
                        <Parachute>
                            <KnownMass>58.12967694762904</KnownMass>
                            <Density>0.006700000000000001</Density>
                            <Material>Ripstop nylon</Material>
                            <Name>Parachute</Name>
                            <KnownCG>36.00000000000001</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>48.0</Xb>
                            <CalcMass>58.12967694762904</CalcMass>
                            <CalcCG>36.00000000000001</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>72.00000000000001</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>2</SerialNo>
                            <Dia>1000.0</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>510.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0018</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Elastic cord (round 2 mm, 1/16 in)</ShroudLineMaterial>
                            <DragCoefficient>0.8</DragCoefficient>
                        </Parachute>
                    </AttachedParts>
                    <BaseDia>92.0</BaseDia>
                    <ShoulderLen>0.0</ShoulderLen>
                    <ShoulderOD>0.0</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>875.7126690028477</KnownMass>
                    <Density>1780.0</Density>
                    <Material>Carbon fiber</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>180.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>875.7126690028477</CalcMass>
                    <CalcCG>180.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>360.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>3</SerialNo>
                    <OD>92.0</OD>
                    <ID>82.0</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>82.0</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <BodyTube>
                            <KnownMass>24.609980211161044</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Inner Tube</Name>
                            <KnownCG>60.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-100.0</Xb>
                            <CalcMass>24.609980211161044</CalcMass>
                            <CalcCG>60.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>120.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>4</SerialNo>
                            <OD>50.0</OD>
                            <ID>46.0</ID>
                            <IsMotorMount>0</IsMotorMount>
                            <MotorDia>46.0</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts>
                                <MassObject>
                                    <KnownMass>476.3282781372844</KnownMass>
                                    <Density>0.0</Density>
                                    <Material></Material>
                                    <Name>Mass Component</Name>
                                    <KnownCG>5.0</KnownCG>
                                    <UseKnownCG>1</UseKnownCG>
                                    <Xb>5.0</Xb>
                                    <CalcMass>0.0</CalcMass>
                                    <CalcCG>0.0</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>0</LocationMode>
                                    <Len>110.0</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>5</SerialNo>
                                    <TypeCode>0</TypeCode>
                                </MassObject>
                            </AttachedParts>
                        </BodyTube>
                        <MassObject>
                            <KnownMass>470.00000000000006</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass Component</Name>
                            <KnownCG>4.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>4.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>230.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>2.12</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock Cord</Name>
                            <KnownCG>250.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>250.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>60.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
                <Transition>
                    <KnownMass>122.55812646515616</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>Transition</Name>
                    <KnownCG>33.38441722482727</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>122.55812646515616</CalcMass>
                    <CalcCG>33.38441722482727</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>85.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>8</SerialNo>
                    <ShapeCode>0</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>5.0</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <FrontShoulderLen>40.0</FrontShoulderLen>
                    <RearShoulderLen>40.0</RearShoulderLen>
                    <FrontShoulderDia>86.0</FrontShoulderDia>
                    <RearShoulderDia>50.0</RearShoulderDia>
                    <FrontDia>92.0</FrontDia>
                    <RearDia>68.0</RearDia>
                </Transition>
                <BodyTube>
                    <KnownMass>792.6709503905089</KnownMass>
                    <Density>1780.0</Density>
                    <Material>Carbon fiber</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>225.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>792.6709503905089</CalcMass>
                    <CalcCG>225.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>450.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>9</SerialNo>
                    <OD>68.0</OD>
                    <ID>58.0</ID>
                    <IsMotorMount>1</IsMotorMount>
                    <MotorDia>58.0</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <FinSet>
                            <KnownMass>257.01453583905527</KnownMass>
                            <Density>1850.0</Density>
                            <Material>Fiberglass</Material>
                            <Name>Trapezoidal Fin Set</Name>
                            <KnownCG>81.4644286992774</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>408.37912623471874</CalcMass>
                            <CalcCG>81.4644286992774</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>10</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>120.0</RootChord>
                            <TipChord>67.0</TipChord>
                            <SemiSpan>85.0</SemiSpan>
                            <SweepDistance>89.46482483062626</SweepDistance>
                            <Thickness>6.0</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>2</TipShapeCode>
                            <TabLength>60.0</TabLength>
                            <TabDepth>6.999999999999999</TabDepth>
                            <TabOffset>35.000000000000014</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <Ring>
                            <KnownMass>46.699303556714256</KnownMass>
                            <Density>630.0</Density>
                            <Material>Plywood (birch)</Material>
                            <Name>Centering Ring.</Name>
                            <KnownCG>26.000000000000004</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>160.0</Xb>
                            <CalcMass>46.699303556714256</CalcMass>
                            <CalcCG>26.000000000000004</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>52.00000000000001</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <OD>68.0</OD>
                            <ID>53.0</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>4.269895655126569</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Centering Ring.</Name>
                            <KnownCG>2.5</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>25.0</Xb>
                            <CalcMass>4.269895655126569</CalcMass>
                            <CalcCG>2.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>5.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>12</SerialNo>
                            <OD>68.0</OD>
                            <ID>55.0</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>11.439795488781874</KnownMass>
                            <Density>630.0</Density>
                            <Material>Plywood (birch)</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>2.5</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>243.00000000000003</Xb>
                            <CalcMass>11.439795488781874</CalcMass>
                            <CalcCG>2.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>5.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>13</SerialNo>
                            <OD>68.0</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>3.9559327393084396</KnownMass>
                            <Density>630.0</Density>
                            <Material>Plywood (birch)</Material>
                            <Name>Centering Ring</Name>
                            <KnownCG>2.5</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>3.9559327393084396</CalcMass>
                            <CalcCG>2.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>5.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>14</SerialNo>
                            <OD>68.0</OD>
                            <ID>55.0</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Parachute>
                            <KnownMass>7.975950925286614</KnownMass>
                            <Density>0.006700000000000001</Density>
                            <Material>Ripstop nylon</Material>
                            <Name>Parachute</Name>
                            <KnownCG>28.999999999999996</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>50.0</Xb>
                            <CalcMass>7.975950925286614</CalcMass>
                            <CalcCG>28.999999999999996</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>57.99999999999999</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>15</SerialNo>
                            <Dia>300.0</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>300.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0018</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Elastic cord (round 2 mm, 1/16 in)</ShroudLineMaterial>
                            <DragCoefficient>0.8</DragCoefficient>
                        </Parachute>
                        <MassObject>
                            <KnownMass>3.6</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock Cord</Name>
                            <KnownCG>115.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>115.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>79.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>16</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Ring>
                            <KnownMass>33.0</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Centering Ring.</Name>
                            <KnownCG>2.5</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>99.0</Xb>
                            <CalcMass>4.560964214481661</CalcMass>
                            <CalcCG>2.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>5.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>17</SerialNo>
                            <OD>68.0</OD>
                            <ID>54.00000000000001</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>